default_language_version:
  python: python3
repos:
  # Checking Hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      - id: check-json
        exclude: |
          (?x)^(
            .devcontainer/devcontainer.json|
            .vscode/settings.default.json
          )$
      - id: check-yaml
      - id: check-toml
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: mixed-line-ending
        args:
          - "--fix"
          - "no"
      - id: name-tests-test
        args:
          - "--pytest"
      - id: pretty-format-json
        exclude: |
          (?x)^(
            .devcontainer/devcontainer.json|
            .vscode/settings.default.json
          )$

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "v1.9.0"
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations

  # Check editor-config compliance
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "2.6.1"
    hooks:
      - id: editorconfig-checker
        exclude_types:
          - "jupyter"

  # Auto upgrade code with python 3.10 peps
  - repo: https://github.com/asottile/pyupgrade
    rev: "v2.38.2"
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  # Formatting Hooks
  - repo: https://github.com/PyCQA/isort
    rev: "5.10.1"
    hooks:
      - id: isort
        args: [--check]
  - repo: https://github.com/psf/black
    rev: "22.8.0"
    hooks:
      - id: black
        args: [--check]
      - id: black-jupyter
        args: [--check]

  # Linting Hooks
  - repo: https://github.com/PyCQA/flake8
    rev: "5.0.4"
    hooks:
      - id: flake8
        additional_dependencies:
          - "flake8-bugbear>=22.9.23"
          - "flake8-docstrings>=1.6.0"

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: "v0.5.1"
    hooks:
      - id: markdownlint-cli2

  # Type checking Hooks
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.981"
    hooks:
      - id: mypy
        exclude: tests/
        args:
          - "--no-incremental"
        additional_dependencies:
          - "numpy"

  # Security checking Hooks
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit
        additional_dependencies: ["toml"]
        args:
          - "-c"
          - "pyproject.toml"
exclude: |
  (?x)^(
    assets/|
    data/|
    slides/
  ).+$
